name: valuatorx
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  flutter_dotenv: ^5.2.1
  flutter_map: ^7.0.2
  flutter_map_cache: ^2.0.0
  flutter_map_marker_cluster: ^1.4.0
  geolocator: ^11.0.0
  http_cache_hive_store: ^5.0.0
  latlong2: ^0.9.1
  oauth2: ^2.0.1
  provider: ^6.1.4
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
