name: valuatorx
description: "Create and manage valuation reports and more with ValuatorX"
publish_to: 'none'
version: 1.0.5+35
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  collection: ^1.19.1
  flutter_dotenv: ^5.2.1
  flutter_map: ^7.0.2
  flutter_map_cache: ^2.0.0
  flutter_map_marker_cluster: ^1.4.0
  flutter_quill: ^11.4.1
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  http_cache_hive_store: ^5.0.0
  hive_ce: ^2.11.3
  image: ^4.0.17
  image_picker: ^1.1.2
  intl: ^0.20.2
  latlong2: ^0.9.1
  markdown_quill: ^4.3.0
  oauth2: ^2.0.1
  provider: ^6.1.4
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.0.0
  markdown: ^7.3.0
  flutter_compass: ^0.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo_mono.png
    - .env
module:
  androidX: true
